
[createrailwaysnavigator_common_config]

	[createrailwaysnavigator_common_config.permissions]
		#Minimum permission level required to edit the global navigator settings. 0 allows everyone to edit these settings. (Default: 0)
		#Range: 0 ~ 4
		global_settings_permission_level = 0
		#Minimum permission level required to use admin features in CRN. 0 gives everybody admin permissions in CRN (not recommended), -1 disables admin features. (Default: 3)
		#Range: -1 ~ 4
		admin_mode_permission_level = 3

	[createrailwaysnavigator_common_config.navigation]
		#If activated, used trains are excluded from the route search for all following route parts. This prevents the same train from being suggested multiple times in the same route and forces the navigator to use other trains instead. Normally, however, there are no problems, so this option can be left off if in doubt. (Default: OFF)
		exclude_trains = false
		#How much transfers should be avoided. Higher values try to use fewer transfers, even if this increases the travel time. (Default: 10000)
		#Range: > 1000
		transfer_cost = 10000

	[createrailwaysnavigator_common_config.train_data_calculation]
		#When activated, CRN calculates the transit times of the trains and does not use the calculations from Create. CRN is much more accurate, while Create calculates an average. (Default: ON)
		custom_transit_time_calculation = true
		#When activated, CRN uses the transit times provided by Create (if available) when initializing. When turned off, the initialization may take longer. (Default: ON)
		use_create_transit_times_on_init = true
		#[in Cycles]
		#How often the calculated time for a route section between two stations must deviate from the current reference value before the reference value is updated. (Default: 3)
		#Range: 1 ~ 16
		total_duration_deviation_buffer_size = 3
		#[in Ticks]
		#Deviations of the calculated time for a route section between two stations from the reference value that are smaller than the threshold value are not taken into account. (Default: 50)
		#Range: 0 ~ 1000
		total_duration_deviation_threshold = 50
		#[in Ticks]
		#How many ticks the real-time can deviate from the scheduled time before the train is considered delayed. (Default: 500)
		#Range: 100 ~ 24000
		schedule_deviation_threshold = 500
		#[In Cycles]
		#(ONLY WORKS FOR TRAINS WITH DYNAMIC DELAYS! Trains without dynamic delays do this every new schedule section by default.)
		# 
		#Every X cycles the scheduled times are updated to the current real-time data. (Default: 2; Disabled: 0)
		#Range: > 0
		auto_reset_timings = 2

	[createrailwaysnavigator_common_config.debug]
		#Prints more details to the console to better observe the behavior of CRN. Only relevant for debugging.
		advanced_logging = false

	[createrailwaysnavigator_common_config.experimental]
		#The new simulation algorithm calculates the times step by step for the respective stations and pays attention to the schedule conditions instead of adding up the total journey time until the desired time is reached. This should lead to more precise results, especially when using time based departure times. (Default: OFF)
		use_new_simulation_algorithm = false

	[createrailwaysnavigator_common_config.advanced_display]
		#Automatically changes the display type when a display link is connected, depending on what should be displayed. (Default: ON)
		auto_change_display_type = true

	[createrailwaysnavigator_common_config.general]
		#[in Ticks]
		#The next stop or information about the start of the journey is announced in the specified number of ticks before the scheduled arrival at the next station. (Default: 600, 30 real life seconds)
		#Range: 100 ~ 1000
		next_stop_announcement = 600
		#[in Ticks]
		#This value indicates how accurately the real-time data should be displayed. By default, only deviations above 10 in-game minutes (167 ticks, approx. 8 real life seconds) are displayed. The lower the value, the more accurate the real-time data but also the more often deviations from the schedule occur. (Default: 167, 10 in-game minutes)
		#Range: 1 ~ 1000
		realtime_precision_threshold = 167
		#[in Ticks]
		#How early a train should be shown on the display. (Default: 1200, 1 real life minute)
		#Range: 100 ~ 24000
		display_lead_time = 1200

